name: Tag Docker Image CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag bangbang93/openbmclapi:${{env.RELEASE_VERSION}}
      - name: Login to docker hub
        run: docker login -u ${{secrets.HUB_USERNAME}} -p ${{secrets.HUB_PASSWORD}}
      - name: Publish image
        run: docker push bangbang93/openbmclapi:${{env.RELEASE_VERSION}}
